# Generated by Django 5.0.3 on 2024-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inventory_updated_at_alter_inventory_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.AddField(
            model_name='inventory',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
